### ISSUE TITLE
Javascript files of Nuget package

### ISSUE THREAD

**Issue by fredgate** [jamez14/bootstrap-sass-nuget#1]
Why are the javascript files placed in the folder javascripts instead of the folder Scripts as is the case for all other packages ?
It would allow applications that use this package to remain consistent and to avoid having multiple folders.

Initially reported here : https://github.com/twbs/bootstrap-sass/issues/886

**Comment by jamesmosier** [comment]
@fredgate sorry for the delay. This issue somehow got past me. I will fix this in the next version of Bootstrap released, presumably 3.3.6. The reason I am waiting is because Nuget doesn't allow you to edit or overwrite a previously published package, therefore it may cause confusion if I bump the package number on my own.

**Comment by jamesmosier** [comment]
@fredgate after reviewing your comment again, I was hoping to get some clarity on the issue. Although the NuGet package source contents have the JS files in the `javascripts` folder, when the NuGet package is installed in Visual Studio it puts them in the `Scripts` folder of the solution. I've attached an image of what I see when installing the package.

Let me know your thoughts. 

![screen shot 2015-07-05 at 11 38 43 am](https://cloud.githubusercontent.com/assets/2854919/8512317/0cc5c666-230b-11e5-9d53-b4e940b87d61.png)

**Comment by jamesmosier** [comment]
Closing for now, as it appears to not be an issue at this time.
